# Generated by Django 2.0.1 on 2018-01-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('num_bedrooms', models.IntegerField()),
                ('property_type', models.CharField(choices=[('FLAT_APARTMENT', 'Flat / Apartment'), ('HOUSE', 'House'), ('BUNGALOW', 'Bungalow'), ('FARM_LAND', 'Farm / Land'), ('COMMERCIAL_PROPERTY', 'Commercial Property'), ('OTHER', 'Other')], max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=50)),
                ('shared_ownership_scheme', models.CharField(max_length=50)),
                ('new_development', models.CharField(max_length=50)),
                ('size_sq_ft', models.FloatField()),
                ('size_sq_m', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SharedOwnershipScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
